variables:
  clippy_toolchain: 1.36.0
  minimum_toolchain: 1.31.0

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/resources
      endpoint: tabbyssl

jobs:
- job: native_build
  strategy:
    matrix:
      x86_64_linux:
        arch: 'x86_64_linux'
        imageName: 'ubuntu-16.04'
      x86_64_darwin:
        arch: 'x86_64_darwin'
        imageName: 'macos-10.13'
      x86_64_windows_msvc:
        arch: 'x86_64_windows_msvc'
        imageName: 'vs2017-win2016'
  pool:
    vmImage: $(imageName)
  steps:
    - template: az-pipeline/unstable/rustup.yml@templates
    - template: ci/azure/native_build.yml
    - template: ci/azure/pack.yml
    - template: ci/azure/release.yml

- job: cross_build
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      arm_linux:
        rustup_target: 'arm-unknown-linux-gnueabi'
        c_target: 'arm-linux-gnueabi'
        arch: 'arm_linux'
      aarch64_linux:
        rustup_target: 'aarch64-unknown-linux-gnu'
        c_target: 'aarch64-linux-gnu'
        arch: 'aarch64_linux'
      arm_android:
        rustup_target: 'armv7-linux-androideabi'
        c_target: 'arm-linux-androideabi'
        arch: 'armv7_android'
      aarch64_android:
        rustup_target: 'aarch64-linux-android'
        c_target: 'aarch64-linux-android'
        arch: 'aarch64_android'
      x86_64_android:
        rustup_target: 'x86_64-linux-android'
        c_target: 'x86_64-linux-android'
        arch: 'x86_64_android'
      x86_64_windows_mingw:
        rustup_target: 'x86_64-pc-windows-gnu'
        c_target: 'x86_64-windows-gnu'
        arch: 'x86_64_windows_mingw'
  steps:
    - template: az-pipeline/unstable/rustup.yml@templates
      parameters:
        rustup_target: $(rustup_target)
    - template: ci/azure/cross_build.yml
      parameters:
        c_target: $(c_target)
    - template: ci/azure/pack.yml
    - template: ci/azure/release.yml
- template: az-pipeline/unstable/rustfmt.yml@templates
- template: az-pipeline/unstable/clippy.yml@templates
  parameters:
    rustup_toolchain: ${{ variables.clippy_toolchain }}
- job: coverage
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: ci/azure/coverage.yml

trigger:
  branches:
    include:
      - master
      - develop
  tags:
    include:
      - v*
