name: Check Style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'style skip')"

    steps:
      - name: Checkout
        uses: actions/checkout@v1
             
      - name: Check BUILD.bazel and WORKSPACE
        run: |
          go get -u github.com/bazelbuild/buildtools/buildifier
          "$(go env GOPATH)/bin/buildifier" -d -r .

      - name: Check .c and .h
        run: |
          git ls-files | grep '\.c$\|\h$' | xargs --no-run-if-empty -d'\n' clang-format -i --style=Google --dry-run